### ISSUE TITLE
The website should generate links to reference issues

### ISSUE THREAD

**Issue by Milo123459** [rustsec/rustsec#470] opened 2021-11-11 21:28 UTC
https://rustsec.org/advisories/RUSTSEC-2020-0071.html At the bottom of this page at the references section, it should possibly generate a link to that issue (which would be `https://github.com/time-rs/time/issues/293`).

**Comment by amousset** [comment] 2021-11-11 23:28
Here the reference section is not generated by the website but part of the description (see https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/time/RUSTSEC-2020-0071.md), so there is no meaningful way to automatically put a link here, it should be a markdown link in the source.

However the link to the issue is already part of the metadata (in the `url` field), so there is probably no need to repeat it in the description, and the section could be removed completely.

**Comment by amousset** [comment] 2022-08-28 20:55
Closing as explained, the bug is in the advisory description (opened https://github.com/rustsec/advisory-db/pull/1393 to fix it).

**Closed by amousset** 2022-08-28 20:55 UTC
Labels: web
