### ISSUE TITLE
gix version is out of date, causes major duplication

### ISSUE THREAD

**Issue by kornelski** [rustsec/rustsec#1065] opened 2023-11-17 01:36 UTC
Please keep your `gix` version up-to-date, and make frequent `rustsec` releases to keep up with it. 

`gix` is churning through incompatible major versions very fast, and it's hard to sync its version across other crates using it, like `crates-index`. It's a big dependency, so having duplicate copies of all of the `gix` crates is a pain.

**Comment by Shnatsel** [comment] 2023-11-17 01:43
Thank you for the feedback!

I have updated `gix` yesterday in https://github.com/rustsec/rustsec/pull/1061, but have not yet cut a release.

To clarify, the issue is primarily about the binary size and compilation times? We have tried to be careful not to expose `gix` in the public API, so there shouldn't be any SemVer incompatibilities at least.

**Comment by kornelski** [comment] 2023-11-17 02:31
Thank you. 

Yes, it's about compilation and binary overhead.

**Comment by Shnatsel** [comment] 2023-11-17 16:20
I've just published a new version that upgraded to gix 0.55.

Is there a good way to be notified when there's a new release of a particular crate? We can rely on dependabot it it can lag behind in my experience.

**Comment by kornelski** [comment] 2023-11-17 18:18
Threre's renovate bot (https://www.mend.io/renovate/) that can be scheduled to check for updates more frequently, but I think even dependabot would be fine.

**Comment by Shnatsel** [comment] 2023-11-17 18:21
All right!

I'll close this now that an up-to-date release has shipped. Please feel free to prod us if we go without the latest `gix` for a long time.

**Closed** 2023-11-17 18:28 UTC
