### ISSUE TITLE
cargo-audit install fails with rust 1.80

### ISSUE THREAD

**Issue by alexheretic** [rustsec/rustsec#1217] opened 2024-07-25 13:45 UTC
`cargo install cargo-audit --locked` fails using recently released rust 1.80.

Note: `cargo +1.79 install cargo-audit --locked` works.

OS: Linux x86_64

```
$ cargo install cargo-audit --force --locked
    Updating crates.io index
  Installing cargo-audit v0.20.0
    Updating crates.io index
    Updating crates.io index
   Compiling time v0.3.32
error[E0282]: type annotations needed for `Box<_>`
  --> /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.32/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
error: failed to compile `cargo-audit v0.20.0`, intermediate artifacts can be found at `/home/alex/.cache/cargo/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Building without `--locked` also fails
```
error[E0283]: type annotations needed
  --> /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-credentials-0.24.3/src/program/mod.rs:83:63
   |
83 |                 gix_command::prepare(gix_path::from_bstr(args.as_ref()).into_owned())
   |                                                               ^^^^^^
   |
   = note: multiple `impl`s satisfying `BString: AsRef<_>` found in the `bstr` crate:
           - impl AsRef<BStr> for BString;
           - impl AsRef<[u8]> for BString;
help: try using a fully qualified path to specify the expected types
   |
83 |                 gix_command::prepare(gix_path::from_bstr(<BString as AsRef<T>>::as_ref(&args)).into_owned())
   |                                                          +++++++++++++++++++++++++++++++    ~

error[E0283]: type annotations needed
   --> /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-credentials-0.24.3/src/program/mod.rs:83:38
    |
83  |                 gix_command::prepare(gix_path::from_bstr(args.as_ref()).into_owned())
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for reference `&_`
    |
    = note: multiple `impl`s satisfying `Cow<'_, BStr>: From<&_>` found in the `bstr` crate:
            - impl<'a> From<&'a BStr> for Cow<'a, BStr>;
            - impl<'a> From<&'a BString> for Cow<'a, BStr>;
    = note: required for `&_` to implement `Into<Cow<'_, BStr>>`
note: required by a bound in `from_bstr`
   --> /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-path-0.10.9/src/convert.rs:135:34
    |
135 | pub fn from_bstr<'a>(input: impl Into<Cow<'a, BStr>>) -> Cow<'a, Path> {
    |                                  ^^^^^^^^^^^^^^^^^^^ required by this bound in `from_bstr`

   Compiling quitters v0.1.0
For more information about this error, try `rustc --explain E0283`.
error: could not compile `gix-credentials` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-audit v0.20.0`, intermediate artifacts can be found at `/home/alex/.cache/cargo/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by tarcieri** [comment] 2024-07-25 13:55
https://github.com/time-rs/time/issues/693

Removing `--locked` should fix the issue. We can get a release out with this dependency updated.

**Comment by Shnatsel** [comment] 2024-07-25 14:03
The `cargo audit` currently in git relies on some semver-breaking changes in `rustsec`.

I was going to make some further breaking changes in `rustsec` to fix bugs, but my attention is currently elsewhere, so I guess that's not happening anytime soon. We should probably just get the new `rustsec` and `cargo-audit` out of the door; this will get WebAssembly auditing support into a stable release too.

**Comment by alexheretic** [comment] 2024-07-25 14:04
> [time-rs/time#693](https://github.com/time-rs/time/issues/693)
> 
> Removing `--locked` should fix the issue. We can get a release out with this dependency updated.

Building without --locked also fails, for a different reason.

**Comment by tarcieri** [comment] 2024-07-25 14:14
@Shnatsel it would be good to get #1205 landed too since it requires breaking changes

**Comment by Shnatsel** [comment] 2024-07-25 14:16
Sure, sounds good to me. I'm busy with something else though :disappointed:

**Comment by nyanmisaka** [comment] 2024-07-25 14:45
Same issue here. It worked in the previous version.

works: `info: latest update on 2024-06-13, rust version 1.79.0 (129f3b996 2024-06-10)`
failed: `info: latest update on 2024-07-25, rust version 1.80.0 (051478957 2024-07-21)`

```
#8 [stage-0 3/4] RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --no-modify-path &&     cargo install cargo-c && rm -rf "/opt/cargo"/registry "/opt/cargo"/git
#8 0.403 info: downloading installer
#8 0.628 info: profile set to 'default'
#8 0.628 info: default host triple is x86_64-unknown-linux-gnu
#8 0.628 info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
#8 0.744 info: latest update on 2024-07-25, rust version 1.80.0 (051478957 2024-07-21)
...
#8 65.43    Compiling gix-credentials v0.24.3
#8 65.51 error[E0283]: type annotations needed
#8 65.51   --> /opt/cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-credentials-0.24.3/src/program/mod.rs:83:63
#8 65.51    |
#8 65.51 83 |                 gix_command::prepare(gix_path::from_bstr(args.as_ref()).into_owned())
#8 65.51    |                                                               ^^^^^^
#8 65.51    |
#8 65.51    = note: multiple `impl`s satisfying `BString: AsRef<_>` found in the `bstr` crate:
#8 65.51            - impl AsRef<BStr> for BString;
#8 65.51            - impl AsRef<[u8]> for BString;
#8 65.51 help: try using a fully qualified path to specify the expected types
#8 65.51    |
#8 65.51 83 |                 gix_command::prepare(gix_path::from_bstr(<BString as AsRef<T>>::as_ref(&args)).into_owned())
#8 65.51    |                                                          +++++++++++++++++++++++++++++++    ~
#8 65.51 
#8 65.51 error[E0283]: type annotations needed
#8 65.51    --> /opt/cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-credentials-0.24.3/src/program/mod.rs:83:38
#8 65.51     |
#8 65.51 83  |                 gix_command::prepare(gix_path::from_bstr(args.as_ref()).into_owned())
#8 65.51     |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for reference `&_`
#8 65.51     |
#8 65.51     = note: multiple `impl`s satisfying `Cow<'_, BStr>: From<&_>` found in the `bstr` crate:
#8 65.51             - impl<'a> From<&'a BStr> for Cow<'a, BStr>;
#8 65.51             - impl<'a> From<&'a BString> for Cow<'a, BStr>;
#8 65.51     = note: required for `&_` to implement `Into<Cow<'_, BStr>>`
#8 65.51 note: required by a bound in `from_bstr`
#8 65.51    --> /opt/cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-path-0.10.9/src/convert.rs:135:34
#8 65.51     |
#8 65.51 135 | pub fn from_bstr<'a>(input: impl Into<Cow<'a, BStr>>) -> Cow<'a, Path> {
#8 65.51     |                                  ^^^^^^^^^^^^^^^^^^^ required by this bound in `from_bstr`
#8 65.51 
#8 65.57 For more information about this error, try `rustc --explain E0283`.
#8 65.58 error: could not compile `gix-credentials` (lib) due to 2 previous errors
#8 65.58 warning: build failed, waiting for other jobs to finish...
#8 90.16 error: failed to compile `cargo-c v0.10.2+cargo-0.80.0`, intermediate artifacts can be found at `/tmp/cargo-install3AXPbf`.
#8 90.16 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
#8 ERROR: process "/bin/sh -c curl https://sh.rustup.rs -sSf | bash -s -- -y --no-modify-path &&     cargo install cargo-c && rm -rf \"${CARGO_HOME}\"/registry \"${CARGO_HOME}\"/git" did not complete successfully: exit code: 101
```

**Comment by ijackson** [comment] 2024-07-29 08:29
Since evidently this slew of breaking-changes-things aren't going to be ready soon, perhaps we could have an interim release that updates the shipped `Cargo.lock`.  (Cautious people probably use `--locked`, so are currently somewhat stuck.)

**Comment by tarcieri** [comment] 2024-07-29 14:32
I can probably kick some prereleases out today

**Comment by tarcieri** [comment] 2024-07-30 20:48
The following should now work:

```console
$ cargo install cargo-audit --version 0.21.0-pre.0
```

**Comment by Shnatsel** [comment] 2024-07-30 20:55
I can confirm it works on rustc 1.80.0 stable.

**Comment by Shnatsel** [comment] 2024-07-30 20:57
@tarcieri thanks a lot for taking care of this, and also for simplifying our release process! 
This will enable fewer semver breaks and faster releases going forward.

**Comment by Shnatsel** [comment] 2024-07-30 21:00
...but a simple `cargo install cargo-audit` that doesn't use a pre-release also works for me now. I think our dependency crates noticed the breakage and fixed it too.

**Comment by tarcieri** [comment] 2024-07-30 22:12
Confirmed, I was also able to install it. Closing this.

**Closed by tarcieri** 2024-07-30 22:12 UTC
